
-- Fix 4: Drop duplicate audit trigger (keep log_booking_change_trigger only)
DROP TRIGGER IF EXISTS bookings_audit_trg ON public.bookings;

-- Fix 3: Backfill staff_members owner from legacy admin user_roles (idempotent)
INSERT INTO public.staff_members (user_id, role)
SELECT user_id, 'owner'::staff_role
FROM public.user_roles
WHERE role = 'admin'
ON CONFLICT (user_id) DO NOTHING;

-- Fix 6: Strengthen booking_reference protection (no one can change it from client)
CREATE OR REPLACE FUNCTION public.protect_booking_immutable_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  -- booking_reference is generated by create_booking_request and immutable thereafter
  IF NEW.booking_reference IS DISTINCT FROM OLD.booking_reference THEN
    RAISE EXCEPTION 'booking_reference is immutable and cannot be changed after creation';
  END IF;
  IF NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'created_at is immutable';
  END IF;
  IF NEW.id IS DISTINCT FROM OLD.id THEN
    RAISE EXCEPTION 'id is immutable';
  END IF;
  RETURN NEW;
END;
$function$;

-- Fix 5: Operator-level update restrictions enforced at the database
CREATE OR REPLACE FUNCTION public.enforce_operator_update_scope()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  _uid uuid := auth.uid();
BEGIN
  -- Owners (and unauthenticated SECURITY DEFINER calls) bypass these restrictions
  IF _uid IS NULL OR public.is_owner(_uid) THEN
    RETURN NEW;
  END IF;

  -- Only operators reach here. Block changes to identity / customer / scheduling fields.
  IF NEW.name IS DISTINCT FROM OLD.name
     OR NEW.phone IS DISTINCT FROM OLD.phone
     OR NEW.whatsapp IS DISTINCT FROM OLD.whatsapp
     OR NEW.email IS DISTINCT FROM OLD.email
     OR NEW.area IS DISTINCT FROM OLD.area
     OR NEW.property_type IS DISTINCT FROM OLD.property_type
     OR NEW.service IS DISTINCT FROM OLD.service
     OR NEW.starts_at IS DISTINCT FROM OLD.starts_at
     OR NEW.ends_at IS DISTINCT FROM OLD.ends_at
     OR NEW.details IS DISTINCT FROM OLD.details THEN
    RAISE EXCEPTION 'Operators cannot modify customer or scheduling fields. Owner only.';
  END IF;

  -- Status transition rules for operators
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'cancelled' THEN
      RAISE EXCEPTION 'Only the owner can cancel a booking. Use declined or completed instead.';
    END IF;
    IF NOT (
      (OLD.status = 'requested' AND NEW.status IN ('confirmed','declined'))
      OR (OLD.status = 'confirmed' AND NEW.status = 'completed')
    ) THEN
      RAISE EXCEPTION 'Operator status transition not allowed: % -> %', OLD.status, NEW.status;
    END IF;
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS enforce_operator_scope_trg ON public.bookings;
CREATE TRIGGER enforce_operator_scope_trg
  BEFORE UPDATE ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.enforce_operator_update_scope();

-- Ensure no DELETE policy exists (defensive)
DROP POLICY IF EXISTS "Admins delete bookings" ON public.bookings;
DROP POLICY IF EXISTS "Owners delete bookings" ON public.bookings;
DROP POLICY IF EXISTS "Staff delete bookings" ON public.bookings;
